#version 430
layout(local_size_x=256) in;
layout(std430, binding=0) buffer Particles { vec4 P[]; }; // P[i].xy = ตำแหน่ง
layout(std140, binding=1) uniform SeedCfg { vec2 domain; } S;

void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= P.length()) return;
    // สุ่ม y แล้วเริ่มที่ x=0
    float y = fract(sin(float(id)*12.9898)*43758.5453) * S.domain.y;
    P[id] = vec4(0.0, y, 0.0, 0.0);
}
